package ru.yoomoney.sdk.kassa.payments.di.component;

import android.content.Context;
import dagger.internal.DoubleCheck;
import dagger.internal.Factory;
import dagger.internal.InstanceFactory;
import dagger.internal.Provider;
import ru.yoomoney.sdk.kassa.payments.checkoutParameters.TestParameters;
import ru.yoomoney.sdk.kassa.payments.config.d;
import ru.yoomoney.sdk.kassa.payments.config.e;
import ru.yoomoney.sdk.kassa.payments.di.module.C2267a;
import ru.yoomoney.sdk.kassa.payments.di.module.C2268b;
import ru.yoomoney.sdk.kassa.payments.di.module.C2269c;
import ru.yoomoney.sdk.kassa.payments.di.module.C2270d;
import ru.yoomoney.sdk.kassa.payments.di.module.C2271e;
import ru.yoomoney.sdk.kassa.payments.di.module.C2272f;
import ru.yoomoney.sdk.kassa.payments.di.module.C2273g;
import ru.yoomoney.sdk.kassa.payments.di.module.C2275i;
import ru.yoomoney.sdk.kassa.payments.di.module.C2276j;
import ru.yoomoney.sdk.kassa.payments.di.module.C2282p;
import ru.yoomoney.sdk.kassa.payments.di.module.C2283q;
import ru.yoomoney.sdk.kassa.payments.di.module.C2284s;
import ru.yoomoney.sdk.kassa.payments.di.module.C2285t;
import ru.yoomoney.sdk.kassa.payments.di.module.C2286u;
import ru.yoomoney.sdk.kassa.payments.di.module.C2287v;
import ru.yoomoney.sdk.kassa.payments.di.module.C2288w;
import ru.yoomoney.sdk.kassa.payments.di.module.C2289x;
import ru.yoomoney.sdk.kassa.payments.di.module.C2290y;
import ru.yoomoney.sdk.kassa.payments.di.module.C2291z;
import ru.yoomoney.sdk.kassa.payments.di.module.N;
import ru.yoomoney.sdk.kassa.payments.di.module.O;
import ru.yoomoney.sdk.kassa.payments.di.module.P;
import ru.yoomoney.sdk.kassa.payments.di.module.Q;
import ru.yoomoney.sdk.kassa.payments.di.module.S;
import ru.yoomoney.sdk.kassa.payments.di.module.T;
import ru.yoomoney.sdk.kassa.payments.di.module.Y;
import ru.yoomoney.sdk.kassa.payments.di.module.Z;
import ru.yoomoney.sdk.kassa.payments.di.module.e0;
import ru.yoomoney.sdk.kassa.payments.di.module.f0;
import ru.yoomoney.sdk.kassa.payments.di.module.g0;
import ru.yoomoney.sdk.kassa.payments.di.module.h0;
import ru.yoomoney.sdk.kassa.payments.di.module.i0;
import ru.yoomoney.sdk.kassa.payments.di.module.j0;
import ru.yoomoney.sdk.kassa.payments.di.module.k0;
import ru.yoomoney.sdk.kassa.payments.di.module.l0;
import ru.yoomoney.sdk.kassa.payments.di.module.m0;
import ru.yoomoney.sdk.kassa.payments.di.module.n0;
import ru.yoomoney.sdk.kassa.payments.di.module.r;

/* loaded from: classes5.dex */
public final class c {
    public Factory A;
    public Provider B;
    public Provider C;
    public Provider D;
    public Provider E;
    public Provider F;
    public Provider G;
    public Provider H;
    public final Context a;
    public final TestParameters b;
    public final l0 c;
    public Factory d;
    public Provider e;
    public Provider f;
    public Factory g;
    public Provider h;
    public Provider i;
    public Provider j;
    public Provider k;
    public Provider l;
    public Provider m;
    public Z n;
    public Provider o;
    public Provider p;
    public Provider q;
    public Provider r;
    public Provider s;
    public Provider t;
    public Provider u;
    public Provider v;
    public Provider w;
    public Provider x;
    public Provider y;
    public Provider z;

    public c(l0 l0Var, Y y, r rVar, N n, C2288w c2288w, C2282p c2282p, C2267a c2267a, d dVar, e0 e0Var, j0 j0Var, m0 m0Var, C2275i c2275i, Context context, TestParameters testParameters, String str) {
        this.a = context;
        this.b = testParameters;
        this.c = l0Var;
        a(y, rVar, n, c2288w, c2282p, c2267a, dVar, e0Var, j0Var, m0Var, c2275i, context, testParameters, str);
    }

    public final void a(Y y, r rVar, N n, C2288w c2288w, C2282p c2282p, C2267a c2267a, d dVar, e0 e0Var, j0 j0Var, m0 m0Var, C2275i c2275i, Context context, TestParameters testParameters, String str) {
        Factory factoryCreate = InstanceFactory.create(context);
        this.d = factoryCreate;
        Provider provider = DoubleCheck.provider(new n0(m0Var, factoryCreate));
        this.e = provider;
        this.f = DoubleCheck.provider(new T(n, provider));
        Factory factoryCreate2 = InstanceFactory.create(testParameters);
        this.g = factoryCreate2;
        this.h = DoubleCheck.provider(new C2272f(c2267a, this.d, factoryCreate2));
        Provider provider2 = DoubleCheck.provider(new C2284s(rVar));
        this.i = provider2;
        this.j = DoubleCheck.provider(new C2285t(rVar, provider2));
        this.k = DoubleCheck.provider(new C2269c(c2267a, this.d));
        this.l = DoubleCheck.provider(new Q(n, this.e));
        this.m = DoubleCheck.provider(new S(n, this.e, this.g, this.d));
        Z z = new Z(y, this.d, this.g);
        this.n = z;
        this.o = DoubleCheck.provider(new i0(e0Var, z));
        Provider provider3 = DoubleCheck.provider(new P(n, this.e));
        this.p = provider3;
        Provider provider4 = DoubleCheck.provider(new h0(e0Var, this.d, provider3));
        this.q = provider4;
        this.r = DoubleCheck.provider(new g0(e0Var, this.o, provider4));
        Provider provider5 = DoubleCheck.provider(new f0(e0Var, this.o, this.q));
        this.s = provider5;
        Provider provider6 = DoubleCheck.provider(new k0(j0Var, this.n, this.r, provider5));
        this.t = provider6;
        this.u = DoubleCheck.provider(new C2276j(c2275i, provider6, this.n, this.g));
        this.v = DoubleCheck.provider(new O(n, this.g, this.d, this.e));
        this.w = DoubleCheck.provider(new C2291z(c2288w, this.d, this.g));
        Provider provider7 = DoubleCheck.provider(new C2268b(c2267a));
        this.x = provider7;
        Provider provider8 = DoubleCheck.provider(new e(dVar, this.d, this.v, this.g, this.w, provider7));
        this.y = provider8;
        this.z = DoubleCheck.provider(new C2283q(c2282p, this.g, provider8));
        Factory factoryCreate3 = InstanceFactory.create(str);
        this.A = factoryCreate3;
        Provider provider9 = DoubleCheck.provider(new C2290y(c2288w, this.d, this.g, factoryCreate3, this.t));
        this.B = provider9;
        this.C = DoubleCheck.provider(new C2270d(c2267a, this.z, provider9, this.x));
        this.D = DoubleCheck.provider(new C2286u(rVar, this.i));
        this.E = DoubleCheck.provider(new C2287v(rVar));
        this.F = DoubleCheck.provider(new C2271e(c2267a));
        this.G = DoubleCheck.provider(new C2273g(c2267a, this.d));
        this.H = DoubleCheck.provider(new C2289x(c2288w, this.d, this.g, this.A, this.t));
    }
}
