package ru.yoomoney.sdk.kassa.payments;

import sputnik.axmor.com.R;

/* loaded from: classes5.dex */
public final class R$styleable {
    public static final int SpayBnplGraphCompositeView_spay_graph_size = 0;
    public static final int SpayBonusCompositeView_spay_bonus_view_default_color = 0;
    public static final int SpayBonusCompositeView_spay_bonus_view_selected_color = 1;
    public static final int SpayBonusOverallCompositeView_spay_bonus_overall_view_count = 0;
    public static final int SpayDotsLoaderView_spay_loader_anim_duration = 0;
    public static final int SpayDotsLoaderView_spay_loader_dots_dist = 1;
    public static final int SpayDotsLoaderView_spay_loader_dots_radius = 2;
    public static final int SpayDotsLoaderView_spay_loader_dots_view_height = 3;
    public static final int SpayDotsLoaderView_spay_loader_dots_view_width = 4;
    public static final int SpayDotsLoaderView_spay_loader_first_delay_duration = 5;
    public static final int SpayDotsLoaderView_spay_loader_first_dot_color = 6;
    public static final int SpayDotsLoaderView_spay_loader_interpolator = 7;
    public static final int SpayDotsLoaderView_spay_loader_second_delay_duration = 8;
    public static final int SpayDotsLoaderView_spay_loader_second_dot_color = 9;
    public static final int SpayDotsLoaderView_spay_loader_third_dot_color = 10;
    public static final int SpayOtpTextView_android_textColor = 0;
    public static final int SpayOtpTextView_spay_bar_active_color = 1;
    public static final int SpayOtpTextView_spay_bar_enabled = 2;
    public static final int SpayOtpTextView_spay_bar_error_color = 3;
    public static final int SpayOtpTextView_spay_bar_height = 4;
    public static final int SpayOtpTextView_spay_bar_inactive_color = 5;
    public static final int SpayOtpTextView_spay_bar_margin = 6;
    public static final int SpayOtpTextView_spay_bar_margin_bottom = 7;
    public static final int SpayOtpTextView_spay_bar_margin_left = 8;
    public static final int SpayOtpTextView_spay_bar_margin_right = 9;
    public static final int SpayOtpTextView_spay_bar_margin_top = 10;
    public static final int SpayOtpTextView_spay_bar_success_color = 11;
    public static final int SpayOtpTextView_spay_box_margin = 12;
    public static final int SpayOtpTextView_spay_box_margin_bottom = 13;
    public static final int SpayOtpTextView_spay_box_margin_left = 14;
    public static final int SpayOtpTextView_spay_box_margin_right = 15;
    public static final int SpayOtpTextView_spay_box_margin_top = 16;
    public static final int SpayOtpTextView_spay_height = 17;
    public static final int SpayOtpTextView_spay_hide_otp = 18;
    public static final int SpayOtpTextView_spay_hide_otp_drawable = 19;
    public static final int SpayOtpTextView_spay_hide_otp_error_drawable = 20;
    public static final int SpayOtpTextView_spay_length = 21;
    public static final int SpayOtpTextView_spay_otp = 22;
    public static final int SpayOtpTextView_spay_otp_box_background = 23;
    public static final int SpayOtpTextView_spay_otp_box_background_active = 24;
    public static final int SpayOtpTextView_spay_otp_box_background_error = 25;
    public static final int SpayOtpTextView_spay_otp_box_background_inactive = 26;
    public static final int SpayOtpTextView_spay_otp_box_background_success = 27;
    public static final int SpayOtpTextView_spay_otp_box_match_parent = 28;
    public static final int SpayOtpTextView_spay_otp_text_size = 29;
    public static final int SpayOtpTextView_spay_text_typeface = 30;
    public static final int SpayOtpTextView_spay_width = 31;
    public static final int ym_ListItemSwitchWithDescription_ym_description = 1;
    public static final int ym_ListItemSwitchWithDescription_ym_isChecked = 2;
    public static final int ym_ListItemSwitchWithDescription_ym_title = 3;
    public static final int ym_LoadingView_ym_text = 0;
    public static final int[] SpayBnplGraphCompositeView = {R.attr.spay_graph_size};
    public static final int[] SpayBonusCompositeView = {R.attr.spay_bonus_view_default_color, R.attr.spay_bonus_view_selected_color};
    public static final int[] SpayBonusOverallCompositeView = {R.attr.spay_bonus_overall_view_count};
    public static final int[] SpayCircleView = {R.attr.spay_circle_color, R.attr.spay_circle_draw_only_stroke, R.attr.spay_circle_radius, R.attr.spay_circle_stroke_width};
    public static final int[] SpayDotsLoaderView = {R.attr.spay_loader_anim_duration, R.attr.spay_loader_dots_dist, R.attr.spay_loader_dots_radius, R.attr.spay_loader_dots_view_height, R.attr.spay_loader_dots_view_width, R.attr.spay_loader_first_delay_duration, R.attr.spay_loader_first_dot_color, R.attr.spay_loader_interpolator, R.attr.spay_loader_second_delay_duration, R.attr.spay_loader_second_dot_color, R.attr.spay_loader_third_dot_color};
    public static final int[] SpayOtpTextView = {android.R.attr.textColor, R.attr.spay_bar_active_color, R.attr.spay_bar_enabled, R.attr.spay_bar_error_color, R.attr.spay_bar_height, R.attr.spay_bar_inactive_color, R.attr.spay_bar_margin, R.attr.spay_bar_margin_bottom, R.attr.spay_bar_margin_left, R.attr.spay_bar_margin_right, R.attr.spay_bar_margin_top, R.attr.spay_bar_success_color, R.attr.spay_box_margin, R.attr.spay_box_margin_bottom, R.attr.spay_box_margin_left, R.attr.spay_box_margin_right, R.attr.spay_box_margin_top, R.attr.spay_height, R.attr.spay_hide_otp, R.attr.spay_hide_otp_drawable, R.attr.spay_hide_otp_error_drawable, R.attr.spay_length, R.attr.spay_otp, R.attr.spay_otp_box_background, R.attr.spay_otp_box_background_active, R.attr.spay_otp_box_background_error, R.attr.spay_otp_box_background_inactive, R.attr.spay_otp_box_background_success, R.attr.spay_otp_box_match_parent, R.attr.spay_otp_text_size, R.attr.spay_text_typeface, R.attr.spay_width};
    public static final int[] SpayUserDataCompositeView = {R.attr.spay_bank_logo, R.attr.spay_user_icon, R.attr.spay_user_name};
    public static final int[] ym_ErrorView = {R.attr.ym_error_button_text, R.attr.ym_error_text, R.attr.ym_error_title};
    public static final int[] ym_InformerView = {R.attr.ym_InformerAlert_Style, R.attr.ym_InformerViewAction_Style, R.attr.ym_InformerViewAlert_Style, R.attr.ym_InformerViewBonus_Style, R.attr.ym_InformerViewDefault_Style, R.attr.ym_InformerViewPrimaryInverse_Style, R.attr.ym_InformerViewPrimary_Style, R.attr.ym_Informer_Style, R.attr.ym_MessageTextAppearance, R.attr.ym_TipViewDefault_Style, R.attr.ym_TipViewInverse_Style, R.attr.ym_TipViewMarketing_Style, R.attr.ym_TipViewOffer_Style, R.attr.ym_action_text, R.attr.ym_informer_action_appearance, R.attr.ym_informer_action_text, R.attr.ym_informer_enabled, R.attr.ym_informer_left_icon, R.attr.ym_informer_left_icon_padding, R.attr.ym_informer_left_icon_shape, R.attr.ym_informer_left_icon_shape_color, R.attr.ym_informer_left_icon_size, R.attr.ym_informer_left_icon_visible, R.attr.ym_informer_message, R.attr.ym_informer_message_margin, R.attr.ym_informer_message_max_lines, R.attr.ym_informer_right_icon, R.attr.ym_informer_right_icon_color, R.attr.ym_informer_ripple_color, R.attr.ym_message_text, R.attr.ym_show_action};
    public static final int[] ym_ListItemSwitchWithDescription = {R.attr.ym_ListItemSwitchCheckout_Style, R.attr.ym_description, R.attr.ym_isChecked, R.attr.ym_title};
    public static final int[] ym_LoadingView = {R.attr.ym_text};
}
